### ISSUE TITLE
Couldn't loading checkpoint

### ISSUE THREAD

**Issue by tuvshu99** [kuldeepbishnoi/Automatic-Emergency-Braking#2]
I have tried to run test_ebs.py. Got the following error.
I have downloaded the weights.

Traceback (most recent call last):
  File "test_ebs.py", line 20, in <module>
    lane_detection = Lane_Detection(laneNet_weight_path)
  File "/home/essys/Test_codes/Automatic-Emergency-Braking/LaneNet/lane_handler.py", line 75, in __init__
    self.saver.restore(sess=self.sess, save_path=weights_path)
  File "/home/essys/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1268, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: .\LaneNet\BiseNetV2_LaneNet_Tusimple_Model_Weights\tusimple_lanenet.ckpt

**Comment by csoham96** [comment]
I am facing the same did you resolve it?

**Comment by trThanhnguyen** [comment]
Hi @tuvshu99,
As your log suggested, the problem is you're using different OS than the author's, so there were incompatibilities in path conventions.
You can change your path to "./LaneNet/BiseNetV2_LaneNet_Tusimple_Model_Weights/tusimple_lanenet.ckpt"
Hope that help,
Regards.

**Comment by trThanhnguyen** [comment]
Hi @tuvshu99,
Can you share the weight file 'tusimple_lanenet.ckpt' with me, I cannot download it because the link is down.
My email address is: thanhnguyen.ppr@gmail.com
Appreciate it.
